spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/DockerTestDB
    username: postgres
    password: s3cret
    driver-class-name: org.postgresql.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
#
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: default
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug