spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/DockerTestDB
    username: postgres
    password: s3cret
    driver-class-name: org.postgresql.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: localhost
    port: 3025
    username: user1@example.com
    password: doesnotmatter
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.port: 3025
      mail.smtp.starttls.enable: false